In [1]:
import numpy as np

In [2]:
mt = np.array([12, 34, 26, 18, 10])
mt

array([12, 34, 26, 18, 10])

In [5]:
#criar com tipo especifico
mint = np.array([1, 2, 3], dtype = np.int32)
mfloat = np.array([1, 2, 3], dtype = np.float64)
print(mint)
print(mfloat)

[1 2 3]
[1. 2. 3.]


In [6]:
#transformar dados
mt = np.array([12, -34, 26.99, 18, 10])
mtnew = mt.astype(np.int32)
print(mt)
print(mtnew)

[ 12.   -34.    26.99  18.    10.  ]
[ 12 -34  26  18  10]


In [7]:
#mais de uma dimensão
mt2 = np.array([[1,2], [3,4], [5,6]])
mt2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
#arrays tipificados
#matriz 3x2 não inicializada
vazio = np.empty([3,2], dtype = int)
vazio

array([[         0, 1072693248],
       [         0, 1073741824],
       [         0, 1074266112]])

In [10]:
#matriz 4x3 com zeros
zeros = np.zeros([4,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#matriz 5x7 com uns
uns = np.ones([5,7])
print(uns)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [12]:
#matriz quadrada com diagonal 1 e outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
#com valores aleatórios
ale = np.random.random(5)
print(ale)

[0.12547877 0.49699063 0.79112343 0.10344747 0.2404782 ]


In [14]:
#aleatórios contendo negativos
ale2 = np.random.randn(5)
print(ale2)

[ 2.03390689 -1.15877761 -1.69366354  1.64227374 -0.49944516]


In [15]:
#aleatórios 3x4
ale3 = (10 * np.random.random((3,4)))
print(ale3)

[[3.35824321 5.64068496 3.40896859 0.48014791]
 [4.50433281 6.75707197 3.77527806 9.27361875]
 [4.34620303 5.52511507 4.44543342 8.66367181]]


In [16]:
#aleatórios com semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

[0.51182162 0.9504637  0.14415961]


In [17]:
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [18]:
#remove valores repetidos
j = np.array([1,1,1,1,1,2,2,2,2,3,3,3,3])
j = np.unique(j)
print(j)

[1 2 3]


In [19]:
#funções de matriz
k = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(k)
print(k[0][1])
#mostra o tamanho da matriz
print(k.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [20]:
# funcões matemáticas
print(k.max()) #valor máximo
print(k.min()) #minimo
print(k.sum()) #soma
print(k.mean()) #média
print(k.std()) #desvio padrão

9
1
45
5.0
2.581988897471611


In [22]:
k1 = np.array([1,4,9,16,25,36,49,64,81])
print(np.sqrt(k1)) #trás a raiz dos elementos
print(np.exp(k1)) #trás o valor exponencial dos elementos

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15 1.90734657e+21 6.23514908e+27
 1.50609731e+35]


In [23]:
#extração de elementos
m = np.array([12, 34, 26, 18, 10])

#posição dois
print(m[1])
#dois elemntos a partir de 0
print(m[0:2])
#a partir da posição um trás todos os elemntos
print(m[1:])
#dos os elemntos a partir do antipenultimo
print(m[-3:])

34
[12 34]
[34 26 18 10]
[26 18 10]


In [24]:
l = np.array([[1,2], [3,4], [5,6]])
#primeira linha
print(l[0,:])
#segunda linha
print(l[1,:])
print(l[2,:])
#todas as linhas da primeira coluna
print(l[:,0])
#todas as linhas da segunda coluna
print(l[:,1])


[1 2]
[3 4]
[5 6]
[1 3 5]
[2 4 6]


In [25]:
#Adição e multiplicação
a = np.array([[1,2], [3,4]])
b = np.array([[1,1], [1,1]])
res = a + b
res2 = a * b
p = np.array([[1,2], [3,4], [5,6]])
q = np.array([[2,1]])
print(p + q)

[[3 3]
 [5 5]
 [7 7]]


In [26]:
# rearranjo de um conjunto de 15 elementos em 3 x 5
f = np.arange(15).reshape((3,5))
print(f)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
#transposição trocando linha por coluna
s = f.T
print(s)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [28]:
#outra forma
# rearranjo de um conjunto de 15 elementos em 3 x 5
r = np.arange(15).reshape((3,5))
print(f)
#transposição trocando linha por coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [29]:
#expressão lógica
v = np.random.randn(4,4)
print(v)

print(v>0)

z = np.where(v > 0, 1, -1)
print(z)

[[-0.4878032   0.21787638 -0.9159527   2.50012592]
 [-0.47680008  0.68060426 -2.15139854 -1.20822782]
 [ 0.34491229  0.71795186  0.2589909  -1.22944907]
 [-1.1150128   0.19614787 -2.13183438 -0.27347458]]
[[False  True False  True]
 [False  True False False]
 [ True  True  True False]
 [False  True False False]]
[[-1  1 -1  1]
 [-1  1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]]
